### ISSUE TITLE
Example usage for React-Native

### ISSUE THREAD

**Issue by avishayil** [yeliex/jsbridge#1]
Hi, I got here after looking for RN components.
I was wondering how could I communicate with RN WebView.
Can you provide an example or basic explanation?

Thanks!

**Comment by yeliex** [comment]
the `jsbridge` is for `front-end` side and we will provider native side later
you can google `jsbridge with react-native` for more infomation, almost the same as `ios`
there is an article in Chinese may help `http://www.alloyteam.com/2015/05/react-native-zhi-jsbridge/http://www.alloyteam.com/2015/05/react-native-zhi-jsbridge/`
